-- CREATE TABLE users(
--   id SERIAL PRIMARY KEY,
--   name VARCHAR(256),
--   bool BOOlEAN,
--   age INTEGER,
--   created_at timestamp
-- );
-- 
-- CREATE TABLE products(
--   id SERIAL PRIMARY KEY,
--   name VARCHAR(256),
--   price REAL
-- );
-- 
-- CREATE TABLE currency_rates(
--   rate REAL
-- );
-- 
-- CREATE TABLE comments(
--   id SERIAL PRIMARY KEY,
--   parent_id INTEGER
-- );
-- 
-- CREATE TABLE replies(
--   id SERIAL PRIMARY KEY
-- );
-- 
